
name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get list of changed files
        id: changed-files
        run: |
          echo "Diff commit:"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Get changed files
        id: concat-changed-files
        run: echo | 
          "changed_files=tes$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | cut -d'/' -f1)" >> $GITHUB_OUTPUT
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ${{ steps.concat-changed-files.outputs.changed_files }}
          container_name: ${{ steps.concat-changed-files.outputs.changed_files }}/xsl
          connection_string: ${{ secrets.ConnectionString }}
          #extra_args: '--pattern *.xsl'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
 
