name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 130438765
          container_name: 130438765
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: '--pattern *.xml'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
